 #include<iostream>
 using namespace std;
 main(){
	cout<<"Number 1: ";
	int a;
	cin>>a;
	cout<<"Number 2: ";
	int b;
	cin>>b;
	cout<<"Number 3: ";
	int c;
	cin>>c;
	cout<<"Number 4: ";
	int d;
	cin>>d;
	cout<<"Number 5: ";
	int e;
	cin>>e;
	cout<<"Number 6: ";
	int f;
	cin>>f;
	cout<<"Number 7: ";
	int g;
	cin>>g;
	cout<<"Number 8: ";
	int h;
	cin>>h;
	cout<<"Number 9: ";
	int i;
	cin>>i;
	cout<<"Number 10: ";
	int j;
	cin>>j;
	cout<<"Number 11: ";
	int k;
	cin>>k;
	cout<<"Number 12: ";
	int l;
	cin>>l;
	cout<<"Number 13: ";
	int m;
	cin>>m;
	cout<<"Number 14: ";
	int n;
	cin>>n;
	cout<<"Number 15: ";
	int o;
	cin>>o;
	int result;
	result=(a+b+c+d+e)+(f*g*h*i*j)-(k-l-m-n-o);
	cout<<"The final result is: "<<result;
}